//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalaryCalculation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salary
    {
        public int ID { get; set; }
        public int WorkerID { get; set; }
        public string MonthYear { get; set; }
        public decimal Accured { get; set; }
        public decimal Withheld { get; set; }
        public decimal Paid { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
